// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Web — same Firebase project, web platform
  // NOTE: Replace appId with the real web appId from Firebase Console
  // Project Settings → Your apps → Add app → Web → copy appId

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDESaosIX_AMw7dVf50GF8f6VBFMBsnMcU',
    appId: '1:1070622456974:web:561ab90e05086c7b185ddf',
    messagingSenderId: '1070622456974',
    projectId: 'rideal-laundry',
    authDomain: 'rideal-laundry.firebaseapp.com',
    storageBucket: 'rideal-laundry.firebasestorage.app',
    measurementId: 'G-668SMG2HQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeV8lhg-hUWwG5ge6a47UxcTW2JS_6Mgo',
    appId: '1:1070622456974:android:57186895761eba61185ddf',
    messagingSenderId: '1070622456974',
    projectId: 'rideal-laundry',
    storageBucket: 'rideal-laundry.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7oD8NG8XXQrpbROYwMIBX40iM9V33NV8',
    appId: '1:1070622456974:ios:4c7adb2e8e6973d9185ddf',
    messagingSenderId: '1070622456974',
    projectId: 'rideal-laundry',
    storageBucket: 'rideal-laundry.firebasestorage.app',
    iosBundleId: 'com.rds.rideallaundry',
  );
}
